export const FORM_ACTIONS = {
  SET_PRACTITIONER: "SET_PRACTITIONER",
  SET_DATE_FROM: "SET_DATE_FROM",
  SET_DATE_TO: "SET_DATE_TO",
  RESET: "RESET",
  CLEAR_DATES: "CLEAR_DATES"
}

export const CONFIG_ACTIONS = {
  SET_IS_LOADING_PRACTITIONERS: "SET_IS_LOADING_PRACTITIONERS",
  SET_IS_REPORT_GENERATED: "SET_IS_REPORT_GENERATED",
  SET_RECORDS_PER_PAGE: "SET_RECORDS_PER_PAGE",
  SET_CURRENT_REVENUE_PAGE: "SET_CURRENT_REVENUE_PAGE",
  SET_CURRENT_APPOINTMENTS_PAGE: "SET_CURRENT_APPOINTMENTS_PAGE",
  NEXT_REVENUE_PAGE: "NEXT_REVENUE_PAGE",
  PREV_REVENUE_PAGE: "PREV_REVENUE_PAGE",
  NEXT_APPOINTMENTS_PAGE: "NEXT_APPOINTMENTS_PAGE",
  PREV_APPOINTMENTS_PAGE: "PREV_APPOINTMENTS_PAGE",
  SHOW_APPOINTMENTS: "SHOW_APPOINTMENTS",
  SHOW_APPOINTMENT_DETAILS: "SHOW_APPOINTMENT_DETAILS",
  SET_SELECTED_REPORT_MONTH: "SET_SELECTED_REPORT_MONTH",
  RESET: "RESET"
}